/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frs;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;

/**
 *
 * @author Sohan Dutta
 */
public class BookingScreen extends javax.swing.JFrame {

    GUIManager displayManager;
    //Timer for navigation drawer animation
    Timer timerOpen;
    Timer timerClose; 
    //ActionListener for navigation drawer
    ActionListener drawerOpen;   
    ActionListener drawerClose;
    //Selected Flight
    ComboFlight cf;
    /**
     * Constructor for BookingScreen
     * @param displayManager is the instance of the DisplayManager passed through the constructor
     */
    public BookingScreen(GUIManager displayManager) {
        this.displayManager=displayManager;
        this.setTitle("DarkSwag FRS | Book");
        initComponents();
        cf=null;
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Null.png")));
        
        drawerOpen=new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                jSplitPane1.setDividerLocation(jSplitPane1.getDividerLocation()+5); 
                if (jSplitPane1.getDividerLocation()>=200) {
                    jSplitPane1.setDividerLocation(200);    
                    timerOpen.stop();
                }        
            }
        };
        
        drawerClose=new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                jSplitPane1.setDividerLocation(jSplitPane1.getDividerLocation()-5);      
                if (jSplitPane1.getDividerLocation()<=0) {
                    jSplitPane1.setDividerLocation(0);    
                    timerClose.stop();                  
                }
            }
        };
        timerClose = new Timer(10, drawerClose);
        timerOpen = new Timer(10, drawerOpen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lOrigin = new javax.swing.JLabel();
        lDomDept = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lDomArr = new javax.swing.JLabel();
        lIntDept = new javax.swing.JLabel();
        lOrigin_var = new javax.swing.JLabel();
        lDomDept_var = new javax.swing.JLabel();
        lVia_var = new javax.swing.JLabel();
        lDomArr_var = new javax.swing.JLabel();
        lIntDept_var = new javax.swing.JLabel();
        lThrough = new javax.swing.JLabel();
        lThrough_var = new javax.swing.JLabel();
        lIntArr = new javax.swing.JLabel();
        lIntArr_var = new javax.swing.JLabel();
        lDest = new javax.swing.JLabel();
        lDest_var = new javax.swing.JLabel();
        lSpiceJet = new javax.swing.JLabel();
        lSpicejet_var = new javax.swing.JLabel();
        lSilkAir = new javax.swing.JLabel();
        lSilkAir_var = new javax.swing.JLabel();
        lTransitTime = new javax.swing.JLabel();
        lTransitTime_var = new javax.swing.JLabel();
        lTotalTime = new javax.swing.JLabel();
        lTotalTime_var = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        dOrigin = new javax.swing.JLabel();
        dSpiceJet = new javax.swing.JLabel();
        dDeparture = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        dTransit = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        dDestination = new javax.swing.JLabel();
        dSilkAir = new javax.swing.JLabel();
        dArrival = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        dThrough = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(940, 580));
        setPreferredSize(new java.awt.Dimension(940, 580));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setLastDividerLocation(200);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(850, 580));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(850, 580));

        jPanel5.setBackground(new java.awt.Color(105, 240, 174));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        jLabel13.setToolTipText("Open");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search_tab_inactive.png"))); // NOI18N
        jLabel2.setToolTipText("Go to search");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Booking_tab_active.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Confirm_tab_inactive.png"))); // NOI18N
        jLabel31.setToolTipText("Go to confirmation");
        jLabel31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel31MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel31MouseExited(evt);
            }
        });

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Results_tab_inactive.png"))); // NOI18N
        jLabel32.setToolTipText("Go to search results");
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel32MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel32MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jLabel32)
                .addGap(0, 0, 0)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(jLabel31)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMinimumSize(new java.awt.Dimension(850, 580));
        jPanel6.setPreferredSize(new java.awt.Dimension(850, 580));
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel6MouseDragged(evt);
            }
        });
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hamburger.png"))); // NOI18N
        jLabel4.setToolTipText("Close");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 11);
        jPanel6.add(jLabel4, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Confirm_Button.png"))); // NOI18N
        jLabel30.setToolTipText("Confirm flight");
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel30MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel30MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel30MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel30MouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 16, 0, 16);
        jPanel1.add(jLabel30, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel7.setLabelFor(jTextField2);
        jLabel7.setText("Last Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 16, 0, 0);
        jPanel4.add(jLabel7, gridBagConstraints);

        jLabel6.setLabelFor(jTextField1);
        jLabel6.setText("First Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 16, 0, 0);
        jPanel4.add(jLabel6, gridBagConstraints);

        jTextField2.setText("Swag");
        jTextField2.setToolTipText("Enter your last name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 16, 16, 0);
        jPanel4.add(jTextField2, gridBagConstraints);

        jTextField1.setText("Dark");
        jTextField1.setToolTipText("Enter your first name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 16, 0, 0);
        jPanel4.add(jTextField1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 0, 16);
        jPanel6.add(jPanel1, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bookings_title.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 0);
        jPanel6.add(jLabel5, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(641, 200));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Flight Details :-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 0, 8);
        jPanel2.add(jLabel8, gridBagConstraints);

        lOrigin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lOrigin.setText("Origin:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lOrigin, gridBagConstraints);

        lDomDept.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lDomDept.setText("Departure:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lDomDept, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Via:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(jLabel11, gridBagConstraints);

        lDomArr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lDomArr.setText("Arrival:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lDomArr, gridBagConstraints);

        lIntDept.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lIntDept.setText("Departure:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lIntDept, gridBagConstraints);

        lOrigin_var.setText("City (CTY)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lOrigin_var, gridBagConstraints);

        lDomDept_var.setText("00:00 AM. 01/01/2016");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lDomDept_var, gridBagConstraints);

        lVia_var.setText("City (CTY)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lVia_var, gridBagConstraints);

        lDomArr_var.setText("00:00 AM. 01/01/2016");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lDomArr_var, gridBagConstraints);

        lIntDept_var.setText("00:00 AM. 01/01/2016");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lIntDept_var, gridBagConstraints);

        lThrough.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lThrough.setText("Through:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lThrough, gridBagConstraints);

        lThrough_var.setText("City (CTY)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lThrough_var, gridBagConstraints);

        lIntArr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lIntArr.setText("Arrival:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lIntArr, gridBagConstraints);

        lIntArr_var.setText("00:00 AM. 01/01/2016");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lIntArr_var, gridBagConstraints);

        lDest.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lDest.setText("Destination:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lDest, gridBagConstraints);

        lDest_var.setText("Singapore (SIN)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lDest_var, gridBagConstraints);

        lSpiceJet.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lSpiceJet.setText("SpiceJet:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lSpiceJet, gridBagConstraints);

        lSpicejet_var.setText("XX 000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lSpicejet_var, gridBagConstraints);

        lSilkAir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lSilkAir.setText("SilkAir:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lSilkAir, gridBagConstraints);

        lSilkAir_var.setText("XX 000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lSilkAir_var, gridBagConstraints);

        lTransitTime.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lTransitTime.setText("Transit Time:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lTransitTime, gridBagConstraints);

        lTransitTime_var.setText("0h 0h");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lTransitTime_var, gridBagConstraints);

        lTotalTime.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lTotalTime.setText("Total Time:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lTotalTime, gridBagConstraints);

        lTotalTime_var.setText("0h 0h");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(lTotalTime_var, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 0, 16);
        jPanel6.add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel24.setText("From:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel3.add(jLabel24, gridBagConstraints);

        dOrigin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dOrigin.setText("City");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        jPanel3.add(dOrigin, gridBagConstraints);

        dSpiceJet.setText("XX 000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 0, 8);
        jPanel3.add(dSpiceJet, gridBagConstraints);

        dDeparture.setText("00:00 AM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        jPanel3.add(dDeparture, gridBagConstraints);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plane.gif"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(jLabel28, gridBagConstraints);

        dTransit.setText("00:00 AM | 00:00 AM ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        jPanel3.add(dTransit, gridBagConstraints);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plane.gif"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(jLabel34, gridBagConstraints);

        jLabel35.setText("To:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel3.add(jLabel35, gridBagConstraints);

        dDestination.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dDestination.setText("City");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 10);
        jPanel3.add(dDestination, gridBagConstraints);

        dSilkAir.setText("XX 000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 0, 8);
        jPanel3.add(dSilkAir, gridBagConstraints);

        dArrival.setText("00:00 AM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        jPanel3.add(dArrival, gridBagConstraints);

        jLabel39.setText("Through:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel3.add(jLabel39, gridBagConstraints);

        dThrough.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dThrough.setText("City");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        jPanel3.add(dThrough, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 16, 16);
        jPanel6.add(jPanel3, gridBagConstraints);

        jSplitPane1.setRightComponent(jPanel6);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        timerClose.start();
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hamburger.png"))); // NOI18N
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Null.png"))); // NOI18N
        timerOpen.start();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search_tab_hover.png")));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search_tab_inactive.png")));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Booking_tab_hover.png"))); // NOI18N
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Booking_tab_active.png"))); // NOI18N
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel30MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseEntered
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Confirm_Button_hover.png"))); // NOI18N
    }//GEN-LAST:event_jLabel30MouseEntered

    private void jLabel30MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseExited
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Confirm_Button.png"))); // NOI18N
    }//GEN-LAST:event_jLabel30MouseExited

    private void jLabel30MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MousePressed
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Confirm_Button_pressed.png"))); // NOI18N
    }//GEN-LAST:event_jLabel30MousePressed

    private void jLabel30MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseReleased
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Confirm_Button.png"))); // NOI18N
    }//GEN-LAST:event_jLabel30MouseReleased

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        if (cf==null)
            JOptionPane.showMessageDialog(null,"No flight is selected!","Warning!", JOptionPane.WARNING_MESSAGE);
        else if(jTextField1.getText().toString().length()<=0)
            JOptionPane.showMessageDialog(null," Please enter your first name!","Warning!", JOptionPane.WARNING_MESSAGE);
        else if (jTextField2.getText().toString().length()<=0)
            JOptionPane.showMessageDialog(null," Please enter your last name!","Warning!", JOptionPane.WARNING_MESSAGE);
        else {
            displayManager.bookFlight(jTextField1.getText().toString().trim()+ " "
                                      + jTextField2.getText().toString().trim());
            displayManager.setConfirmationDetails();
            cf=null;
            displayManager.showConfirmationScreen();
        }
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        displayManager.showInputScreen();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Object[] options = {"Yes","No"};
        int confirm = JOptionPane.showOptionDialog(null, "Thank you for flying with us!\nAre you sure you want to exit?", "Exit", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (confirm == 0) {
           System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jLabel32MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseEntered
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Results_tab_hover.png")));
    }//GEN-LAST:event_jLabel32MouseEntered

    private void jLabel32MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseExited
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Results_tab_inactive.png")));
    }//GEN-LAST:event_jLabel32MouseExited

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        displayManager.showSearchResultScreen();
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel31MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseEntered
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Confirm_tab_hover.png")));
    }//GEN-LAST:event_jLabel31MouseEntered

    private void jLabel31MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseExited
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Confirm_tab_inactive.png")));
    }//GEN-LAST:event_jLabel31MouseExited

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        displayManager.showConfirmationScreen();
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jPanel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseDragged
        if(jSplitPane1.getDividerLocation()==200) {        
            timerClose.start();           
        }
        else if(jSplitPane1.getDividerLocation()==1) {
            timerOpen.start();
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Null.png")));
        }
    }//GEN-LAST:event_jPanel6MouseDragged

    /**
     * Formats a 24hour format time to 12hour format
     * @param date is the date to be formatted
     * @return formated date 12 hour format
     */
    private String dateFormatter(String date) {
        String hr=date.substring(0, 2);
        String min=date.substring(2, 4);
        String time=hr+":"+min;
        String formatTime=null;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("H:mm");
            SimpleDateFormat sdf12 = new SimpleDateFormat("KK:mm aa");
            Date dateObj = sdf.parse(time);
            formatTime=sdf12.format(dateObj).toString();
        }
        catch (ParseException e) {
            e.printStackTrace();
        }
        return formatTime;
    }
    /**
     * Formats the city name in title case
     * @param name is the city name to be formatted
     * @return the formatted city name
     */
    private String cityNameFormatter(String name) {
        if (!name.equalsIgnoreCase("-")) {
            CharSequence ch="(";
            if (name.contains(ch)) {
                String fname=null;
                fname=name.substring(0,1).toUpperCase()+
                        name.substring(1, name.indexOf("(")).toLowerCase()+
                        name.substring(name.indexOf("("), name.length());
                return fname;
            }
            else {
                String fname=null;
                fname=name.substring(0,1).toUpperCase()+name.substring(1, name.length()).toLowerCase();
                return fname;
            }
        }
        else 
            return "-";
    }
    /**
     * Converts the time into hours and minutes
     * @param time the time to be formatted
     * @return formatted time for display
     */
    private String transitimeFormatter(int time) {
        String fTime = time/60 + "h " + time%60 +"m";
        return fTime;
    }
    
    /**
     * Sets the ComboFlight details in the JFrame
     * @param cf is the object of ComboFlight which is to be displayed
     */
    public void setFlightDetails(ComboFlight cf) {
        this.cf=cf;
        Flight spiceJet=cf.getSeg1().getFlight();
        Flight silkAir=cf.getSeg2().getFlight();
        
        DateTimeFormatter dtfOut = DateTimeFormat.forPattern("dd/MM/yyyy");
        
        lOrigin_var.setText(cityNameFormatter(spiceJet.getOrigin()));
        lSpicejet_var.setText(spiceJet.getFlightno());
        lDomDept_var.setText(dateFormatter(spiceJet.getDeparture()) + ", "+
                dtfOut.print( cf.getSeg1().getDepartureDate() ) );
        lDomArr_var.setText(dateFormatter(spiceJet.getArrival())+ ", "+
                dtfOut.print( cf.getSeg1().getArrivalDate()) );
        lVia_var.setText(cityNameFormatter(spiceJet.getVia()));
        lTransitTime_var.setText(transitimeFormatter(cf.getTransitTime()));
        
        lThrough_var.setText(cityNameFormatter(silkAir.getOrigin()));
        lSilkAir_var.setText(silkAir.getFlightno());
        lIntDept_var.setText(dateFormatter(silkAir.getDeparture()) + ", " + 
                dtfOut.print( cf.getSeg2().getDepartureDate() ) );
        lIntArr_var.setText( dateFormatter(silkAir.getArrival()) + ", "+
                dtfOut.print(cf.getSeg2().getArrivalDate() ) );
        lDest_var.setText(cityNameFormatter(silkAir.getDestination()));
        lTotalTime_var.setText(transitimeFormatter(cf.getTotatTravelTime()));
        
        dOrigin.setText(cityNameFormatter(spiceJet.getOrigin()).substring(0, spiceJet.getOrigin().indexOf('(')).trim());
        dThrough.setText(cityNameFormatter(silkAir.getOrigin()).substring(0, silkAir.getOrigin().indexOf('(')).trim());
        dDestination.setText(cityNameFormatter(silkAir.getDestination()).substring(0, silkAir.getDestination().indexOf('(')).trim());
        dSpiceJet.setText(spiceJet.getFlightno());
        dSilkAir.setText(silkAir.getFlightno());
        dDeparture.setText(dateFormatter(spiceJet.getDeparture()));
        dTransit.setText( dateFormatter( spiceJet.getArrival() ) + " | " + 
                dateFormatter(silkAir.getDeparture()));
        dArrival.setText(dateFormatter(silkAir.getArrival()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dArrival;
    private javax.swing.JLabel dDeparture;
    private javax.swing.JLabel dDestination;
    private javax.swing.JLabel dOrigin;
    private javax.swing.JLabel dSilkAir;
    private javax.swing.JLabel dSpiceJet;
    private javax.swing.JLabel dThrough;
    private javax.swing.JLabel dTransit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lDest;
    private javax.swing.JLabel lDest_var;
    private javax.swing.JLabel lDomArr;
    private javax.swing.JLabel lDomArr_var;
    private javax.swing.JLabel lDomDept;
    private javax.swing.JLabel lDomDept_var;
    private javax.swing.JLabel lIntArr;
    private javax.swing.JLabel lIntArr_var;
    private javax.swing.JLabel lIntDept;
    private javax.swing.JLabel lIntDept_var;
    private javax.swing.JLabel lOrigin;
    private javax.swing.JLabel lOrigin_var;
    private javax.swing.JLabel lSilkAir;
    private javax.swing.JLabel lSilkAir_var;
    private javax.swing.JLabel lSpiceJet;
    private javax.swing.JLabel lSpicejet_var;
    private javax.swing.JLabel lThrough;
    private javax.swing.JLabel lThrough_var;
    private javax.swing.JLabel lTotalTime;
    private javax.swing.JLabel lTotalTime_var;
    private javax.swing.JLabel lTransitTime;
    private javax.swing.JLabel lTransitTime_var;
    private javax.swing.JLabel lVia_var;
    // End of variables declaration//GEN-END:variables
}
