/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frs;

import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;

/**
 *
 * @author Sohan Dutta
 */
public class ConfirmationScreen extends javax.swing.JFrame {

    GUIManager displayManager;
    //Timer for navigation drawer animation
    Timer timerOpen;
    Timer timerClose; 
    //ActionListener for navigation drawer
    ActionListener drawerOpen;   
    ActionListener drawerClose;
    
    /**
     * Constructor for ConfirmationScreen
     * @param displayManager is the instance of the DisplayManager passed through the constructor
     */
    public ConfirmationScreen(GUIManager displayManager) {
        this.displayManager=displayManager;
        this.setTitle("DarkSwag FRS | Confirm");
        initComponents();
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Null.png")));
        
        drawerOpen=new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                jSplitPane1.setDividerLocation(jSplitPane1.getDividerLocation()+5); 
                if (jSplitPane1.getDividerLocation()>=200) {
                    jSplitPane1.setDividerLocation(200);    
                    timerOpen.stop();
                }        
            }
        };
        
        drawerClose=new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                jSplitPane1.setDividerLocation(jSplitPane1.getDividerLocation()-5);     
                if (jSplitPane1.getDividerLocation()<=0) {
                    jSplitPane1.setDividerLocation(0);    
                    timerClose.stop();                
                }
            }
        };
        timerClose = new Timer(10, drawerClose);
        timerOpen = new Timer(10, drawerOpen);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        originCityCode = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        throughCityCode = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        destinationCityCode = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        transitTime = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        totalTime = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        noOfPassengers = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 100));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        departureTime = new javax.swing.JLabel();
        thoughtTime = new javax.swing.JLabel();
        arrivalTime = new javax.swing.JLabel();
        spiceJetNumber = new javax.swing.JLabel();
        silkAirNumber = new javax.swing.JLabel();
        departureDate = new javax.swing.JLabel();
        arrivalDate = new javax.swing.JLabel();
        throughDate = new javax.swing.JLabel();
        originCity = new javax.swing.JLabel();
        throughCityName = new javax.swing.JLabel();
        destinationCityName = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        viaCity = new javax.swing.JLabel();
        referenceNumber = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(940, 580));
        setPreferredSize(new java.awt.Dimension(940, 580));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setLastDividerLocation(200);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(850, 580));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(850, 580));

        jPanel1.setBackground(new java.awt.Color(105, 240, 174));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        jLabel1.setToolTipText("Close");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search_tab_inactive.png"))); // NOI18N
        jLabel4.setToolTipText("Go to search");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Booking_tab_inactive.png"))); // NOI18N
        jLabel6.setToolTipText("Go to booking");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Results_tab_inactive.png"))); // NOI18N
        jLabel7.setToolTipText("Go to search results");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Confirm_tab_active.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addGap(54, 54, 54)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(jLabel7)
                .addGap(0, 0, 0)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(jLabel8)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(225, 245, 254));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hamburger.png"))); // NOI18N
        jLabel2.setToolTipText("Close");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 11);
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Confirm_title.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 16, 11, 16);
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Re-search.png"))); // NOI18N
        jLabel57.setToolTipText("Search for another flight");
        jLabel57.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel57MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel57MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel57MouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 11);
        jPanel2.add(jLabel57, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBackground(new java.awt.Color(33, 33, 33));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DARKSWAG");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 16, 8, 16);
        jPanel4.add(jLabel9, gridBagConstraints);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("FLIGHT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 8, 16);
        jPanel4.add(jLabel10, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("RESERVATION");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 8, 16);
        jPanel4.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SYSTEM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 16, 16);
        jPanel4.add(jLabel12, gridBagConstraints);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qr.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 16, 16);
        jPanel4.add(jLabel13, gridBagConstraints);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo-Icon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 0, 16);
        jPanel4.add(jLabel14, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(jPanel4, gridBagConstraints);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        originCityCode.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        originCityCode.setText("CTY");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 8, 16);
        jPanel7.add(originCityCode, gridBagConstraints);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plane.gif"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.weightx = 1.0;
        jPanel7.add(jLabel16, gridBagConstraints);

        throughCityCode.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        throughCityCode.setText("CTY");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 8, 16);
        jPanel7.add(throughCityCode, gridBagConstraints);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plane.gif"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.weightx = 1.0;
        jPanel7.add(jLabel18, gridBagConstraints);

        destinationCityCode.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        destinationCityCode.setText("SIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 8, 16);
        jPanel7.add(destinationCityCode, gridBagConstraints);

        jPanel8.setBackground(new java.awt.Color(224, 224, 224));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        transitTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        transitTime.setText("0h 0m");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 8, 0);
        jPanel8.add(transitTime, gridBagConstraints);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Transit Time");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 16, 0);
        jPanel8.add(jLabel21, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 16, 0);
        jPanel7.add(jPanel8, gridBagConstraints);

        jPanel9.setBackground(new java.awt.Color(224, 224, 224));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        totalTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalTime.setText("0h 0m");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(16, 0, 8, 0);
        jPanel9.add(totalTime, gridBagConstraints);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Total Time");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 16, 0);
        jPanel9.add(jLabel23, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 16, 0);
        jPanel7.add(jPanel9, gridBagConstraints);

        jPanel10.setBackground(new java.awt.Color(224, 224, 224));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        noOfPassengers.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        noOfPassengers.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(16, 0, 8, 16);
        jPanel10.add(noOfPassengers, gridBagConstraints);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Seats");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 16, 16);
        jPanel10.add(jLabel25, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 16, 16);
        jPanel7.add(jPanel10, gridBagConstraints);

        filler1.setBackground(new java.awt.Color(255, 51, 0));
        filler1.setForeground(new java.awt.Color(204, 0, 153));
        filler1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 16, 0);
        jPanel7.add(filler1, gridBagConstraints);

        filler2.setBackground(new java.awt.Color(255, 0, 204));
        filler2.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 16, 0);
        jPanel7.add(filler2, gridBagConstraints);

        filler3.setBackground(new java.awt.Color(224, 224, 224));
        filler3.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 16, 0);
        jPanel7.add(filler3, gridBagConstraints);

        filler4.setBackground(new java.awt.Color(224, 224, 224));
        filler4.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 16, 0);
        jPanel7.add(filler4, gridBagConstraints);

        filler5.setBackground(new java.awt.Color(224, 224, 224));
        filler5.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 16, 0);
        jPanel7.add(filler5, gridBagConstraints);

        filler6.setBackground(new java.awt.Color(224, 224, 224));
        filler6.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 16, 0);
        jPanel7.add(filler6, gridBagConstraints);

        departureTime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        departureTime.setText("00:00 AM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 8, 16);
        jPanel7.add(departureTime, gridBagConstraints);

        thoughtTime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        thoughtTime.setText("00:00 AM | 00:00 AM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 8, 16);
        jPanel7.add(thoughtTime, gridBagConstraints);

        arrivalTime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        arrivalTime.setText("00:00 AM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 8, 16);
        jPanel7.add(arrivalTime, gridBagConstraints);

        spiceJetNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        spiceJetNumber.setText("XX 000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 8, 0);
        jPanel7.add(spiceJetNumber, gridBagConstraints);

        silkAirNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        silkAirNumber.setText("XX 000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 8, 0);
        jPanel7.add(silkAirNumber, gridBagConstraints);

        departureDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        departureDate.setText("01 / 01 / 2016");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 16, 16);
        jPanel7.add(departureDate, gridBagConstraints);

        arrivalDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        arrivalDate.setText("01 / 01 / 2016");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 16, 16);
        jPanel7.add(arrivalDate, gridBagConstraints);

        throughDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        throughDate.setText("01 / 01 / 2016 | 01 / 01 / 2016 ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 16, 16);
        jPanel7.add(throughDate, gridBagConstraints);

        originCity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        originCity.setText("City");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 8, 16);
        jPanel7.add(originCity, gridBagConstraints);

        throughCityName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        throughCityName.setText("City");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 8, 16);
        jPanel7.add(throughCityName, gridBagConstraints);

        destinationCityName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        destinationCityName.setText("Singapore");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 8, 16);
        jPanel7.add(destinationCityName, gridBagConstraints);

        name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name.setText("Mr. Dark Swag");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 16, 16);
        jPanel7.add(name, gridBagConstraints);

        viaCity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        viaCity.setText("via: City (CTY)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 16, 16);
        jPanel7.add(viaCity, gridBagConstraints);

        referenceNumber.setText("12345678");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 16, 16);
        jPanel7.add(referenceNumber, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(jPanel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 16);
        jPanel2.add(jPanel3, gridBagConstraints);

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        timerClose.start();
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hamburger.png")));
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Null.png")));
        timerOpen.start();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search_tab_hover.png")));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search_tab_inactive.png")));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Booking_tab_hover.png")));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Booking_tab_inactive.png")));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        displayManager.showBookingScreen();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Object[] options = {"Yes","No"};
        int confirm = JOptionPane.showOptionDialog(null, "Thank you for flying with us!\nAre you sure you want to exit?", "Exit", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (confirm == 0) {
           System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jLabel57MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel57MouseEntered
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Re-search_hover.png")));
    }//GEN-LAST:event_jLabel57MouseEntered

    private void jLabel57MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel57MouseExited
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Re-search.png")));
    }//GEN-LAST:event_jLabel57MouseExited

    private void jLabel57MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel57MouseClicked
        displayManager.showInputScreen();
    }//GEN-LAST:event_jLabel57MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Results_tab_hover.png")));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Results_tab_inactive.png")));
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        displayManager.showSearchResultScreen();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Confirm_tab_hover.png")));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Confirm_tab_active.png")));
    }//GEN-LAST:event_jLabel8MouseExited

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        if(jSplitPane1.getDividerLocation()==200) {        
            timerClose.start();           
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hamburger.png")));
        }
        else if(jSplitPane1.getDividerLocation()==1) {
            timerOpen.start();
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Null.png")));
        }
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        displayManager.showInputScreen();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * Sets the booking data in the confirmation screen
     * @param booking is the booking object
     */
    public void setDetails(Booking booking) {
        DateTimeFormatter dtfOut = DateTimeFormat.forPattern("dd / MM / yyyy");
        name.setText(booking.getName());
        referenceNumber.setText(booking.getFlightBookingNumber());
        ComboFlight cf=booking.getComboFlight();
        Flight spiceJet=cf.getSeg1().getFlight();
        Flight silkAir=cf.getSeg2().getFlight();
        originCityCode.setText(spiceJet.getOrigin().substring(spiceJet.getOrigin().indexOf('(')+1, spiceJet.getOrigin().indexOf(')') ).trim());
        throughCityCode.setText(silkAir.getOrigin().substring(silkAir.getOrigin().indexOf('(')+1, silkAir.getOrigin().indexOf(')') ).trim());
        destinationCityCode.setText(silkAir.getDestination().substring(silkAir.getDestination().indexOf('(')+1, silkAir.getDestination().indexOf(')') ).trim());
        originCity.setText(spiceJet.getOrigin().substring(0, spiceJet.getOrigin().indexOf('(')).trim());
        throughCityName.setText(silkAir.getOrigin().substring(0, silkAir.getOrigin().indexOf('(')).trim());
        destinationCityName.setText(silkAir.getDestination().substring(0, silkAir.getDestination().indexOf('(')).trim());
        spiceJetNumber.setText(spiceJet.getFlightno());
        silkAirNumber.setText(silkAir.getFlightno());
        viaCity.setText("via: "+spiceJet.getVia().trim());
        
        departureTime.setText(dateFormatter(spiceJet.getDeparture()));
        thoughtTime.setText(dateFormatter(spiceJet.getArrival()) + " | " + dateFormatter(silkAir.getDeparture()));
        arrivalTime.setText(dateFormatter(silkAir.getArrival()));
        
        departureDate.setText(dtfOut.print(cf.getSeg1().getDepartureDate()));
        throughDate.setText( dtfOut.print(cf.getSeg1().getArrivalDate())+" | "+dtfOut.print(cf.getSeg2().getDepartureDate()));
        if (silkAir.getArrival().length()>4) {
            arrivalDate.setText(dtfOut.print(cf.getSeg1().getDepartureDate().plusDays(1)));
        }
        else {
            arrivalDate.setText(dtfOut.print(cf.getSeg1().getDepartureDate()));
        }
        transitTime.setText(transitimeFormatter(cf.getTransitTime()));
        totalTime.setText(transitimeFormatter(cf.getTotatTravelTime()));
        noOfPassengers.setText(""+cf.getNoOfPassenger());
    }
    /**
     * Formats a 24hour format time to 12hour format
     * @param date is the date to be formatted
     * @return formated date 12 hour format
     */
    private String dateFormatter(String date) {
        String hr=date.substring(0, 2);
        String min=date.substring(2, 4);
        String time=hr+":"+min;
        String formatTime=null;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("H:mm");
            SimpleDateFormat sdf12 = new SimpleDateFormat("KK:mm aa");
            Date dateObj = sdf.parse(time);
            formatTime=sdf12.format(dateObj);
        }
        catch (ParseException e) {
            e.printStackTrace();
        }
        return formatTime;
    }
      
    /**
     * Converts the time into hours and minutes
     * @param time the time to be formatted
     * @return formatted time for display
     */
    private String transitimeFormatter(int time) {
        String fTime = time/60 + "h " + time%60 +"m";
        return fTime;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrivalDate;
    private javax.swing.JLabel arrivalTime;
    private javax.swing.JLabel departureDate;
    private javax.swing.JLabel departureTime;
    private javax.swing.JLabel destinationCityCode;
    private javax.swing.JLabel destinationCityName;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel noOfPassengers;
    private javax.swing.JLabel originCity;
    private javax.swing.JLabel originCityCode;
    private javax.swing.JLabel referenceNumber;
    private javax.swing.JLabel silkAirNumber;
    private javax.swing.JLabel spiceJetNumber;
    private javax.swing.JLabel thoughtTime;
    private javax.swing.JLabel throughCityCode;
    private javax.swing.JLabel throughCityName;
    private javax.swing.JLabel throughDate;
    private javax.swing.JLabel totalTime;
    private javax.swing.JLabel transitTime;
    private javax.swing.JLabel viaCity;
    // End of variables declaration//GEN-END:variables
}
