/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frs;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import org.joda.time.DateTime;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;

/**
 *
 * @author Sohan Dutta
 */
public class SearchResultScreen extends javax.swing.JFrame {

    GUIManager displayManager;
    
    ComboFlight[] comboFlights;
    Object[][] flights;
    
    //Timer for navigation drawer animation
    Timer timerOpen;
    Timer timerClose; 
    //ActionListener for navigation drawer
    ActionListener drawerOpen;   
    ActionListener drawerClose;
    
    /**
     * Constructor for SearchResultScrren
     * @param displayManager is the instance of the DisplayManager passed through the constructor
     */
    public SearchResultScreen(GUIManager displayManager) {
        this.displayManager=displayManager;
        this.comboFlights=null;
        flights=null;
        
        initComponents();
        
        this.setTitle("DarkSwag FRS | Results");
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Null.png"))); // NOI18N
        
        drawerOpen=new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                jSplitPane1.setDividerLocation(jSplitPane1.getDividerLocation()+5);     
                if (jSplitPane1.getDividerLocation()>=200) {
                    jSplitPane1.setDividerLocation(200);    
                    timerOpen.stop();
                }        
            }
        };
        
        drawerClose=new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                jSplitPane1.setDividerLocation(jSplitPane1.getDividerLocation()-5);      
                if (jSplitPane1.getDividerLocation()<=0) {
                    jSplitPane1.setDividerLocation(0);    
                    timerClose.stop();          
                }
            }
        };
        timerClose = new Timer(10, drawerClose);
        timerOpen = new Timer(10, drawerOpen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        originCity = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        destinationCity = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        travelDate = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(940, 580));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setLastDividerLocation(200);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hamburger.png"))); // NOI18N
        jLabel5.setToolTipText("Open");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 11);
        jPanel2.add(jLabel5, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(204, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            flights,
            new String [] {
                "SpiceJet", "via", "Dept. Time", "Arrival Time",
                "SilkAir", "From", "Transit Time", "Dept. Time", "Arrival Time",
                "Seats", "Arrival Date"
            }
        ));
        jTable1.setToolTipText("select a flight");
        jTable1.setGridColor(new java.awt.Color(0, 153, 204));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 16, 16);
        jPanel2.add(jPanel3, gridBagConstraints);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SearchResult_title.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 16, 11, 11);
        jPanel2.add(jLabel6, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Booking_Confirm_Button.png"))); // NOI18N
        jLabel7.setToolTipText("Book a flight");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel7MouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 16, 16);
        jPanel4.add(jLabel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel2.add(jPanel4, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(100, 255, 218));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel10.setText("Flights available from:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 11);
        jPanel5.add(jLabel10, gridBagConstraints);

        originCity.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        originCity.setText("City");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 11);
        jPanel5.add(originCity, gridBagConstraints);

        jLabel12.setText("to");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 11);
        jPanel5.add(jLabel12, gridBagConstraints);

        destinationCity.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        destinationCity.setText("Singapore");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 11);
        jPanel5.add(destinationCity, gridBagConstraints);

        jLabel14.setText("on");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 11);
        jPanel5.add(jLabel14, gridBagConstraints);

        travelDate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        travelDate.setText("01/01/2016");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 11);
        jPanel5.add(travelDate, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 16, 16);
        jPanel2.add(jPanel5, gridBagConstraints);

        jSplitPane1.setRightComponent(jPanel2);

        jPanel1.setBackground(new java.awt.Color(105, 240, 174));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        jLabel1.setToolTipText("Close");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search_tab_inactive.png"))); // NOI18N
        jLabel3.setToolTipText("Go to search");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Booking_tab_inactive.png"))); // NOI18N
        jLabel4.setToolTipText("Go to booking");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Results_tab_active.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Confirm_tab_inactive.png"))); // NOI18N
        jLabel9.setToolTipText("Go to confirmation");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(54, 54, 54)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel8)
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        timerClose.start();
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hamburger.png"))); // NOI18N
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        timerOpen.start();
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Null.png"))); // NOI18N
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search_tab_hover.png"))); // NOI18N
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search_tab_inactive.png"))); // NOI18N
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Booking_tab_hover.png"))); // NOI18N
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Booking_tab_inactive.png"))); // NOI18N
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Booking_Confirm_Button_hover.png"))); // NOI18N
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Booking_Confirm_Button.png"))); // NOI18N
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Booking_Confirm_Button_pressed.png"))); // NOI18N
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseReleased
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Booking_Confirm_Button.png"))); // NOI18N
    }//GEN-LAST:event_jLabel7MouseReleased

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        if(jTable1.getSelectedRow() == -1)
            JOptionPane.showMessageDialog(null,"Please select a route!\n",
                    "Warning!", JOptionPane.WARNING_MESSAGE);
        else if (jTable1.getSelectedRows().length>1) {
            JOptionPane.showMessageDialog(null,"Please select an unique route!\n",
                    "Warning!", JOptionPane.WARNING_MESSAGE);
        }
        else {
            
            displayManager.setSelectedFlight(comboFlights[jTable1.getSelectedRow()]);     
            flights=null;
            originCity.setText("CITY (CTY)");
            destinationCity.setText("SINAGAPORE (SIN)");
            travelDate.setText("01/01/2016");
            jTable1.setModel(new DefaultTableModel(
            flights,
            new String [] {
                "SpiceJet", "via", "Dept. Time", "Arrival Time", "Seats",
                "SilkAir", "From", "Transit Time", "Dept. Time", "Arrival Time", 
                "Seats", "Arrival Date"
                }));
            displayManager.showBookingScreen();
        }           
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        displayManager.showBookingScreen();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        displayManager.showInputScreen();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       Object[] options = {"Yes","No"};
        int confirm = JOptionPane.showOptionDialog(null, "Thank you for flying with us!\nAre you sure you want to exit?", "Exit", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (confirm == 0) {
           System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Results_tab_hover.png")));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Results_tab_active.png")));
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Confirm_tab_hover.png")));
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Confirm_tab_inactive.png")));
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        displayManager.showConfirmationScreen();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        if(jSplitPane1.getDividerLocation()==200) {        
            timerClose.start();           
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hamburger.png")));
        }
        else if(jSplitPane1.getDividerLocation()==1) {
            timerOpen.start();
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Null.png")));
        }
    }//GEN-LAST:event_jPanel2MouseDragged

    /**
     * Formats a 24hour format time to 12hour format
     * @param date is the date to be formatted
     * @return formated date 12 hour format
     */
    private String dateFormatter(String date) {
        String hr=date.substring(0, 2);
        String min=date.substring(2, 4);
        String time=hr+":"+min;
        String formatTime=null;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("H:mm");
            SimpleDateFormat sdf12 = new SimpleDateFormat("KK:mm aa");
            Date dateObj = sdf.parse(time);
            formatTime=sdf12.format(dateObj).toString();
        }
        catch (ParseException e) {
            e.printStackTrace();
        }
        return formatTime;
    }
    
    /**
     * Formats the city name in title case
     * @param name is the city name to be formatted
     * @return the formatted city name
     */
    private String cityNameFormatter(String name) {
        if (!name.equalsIgnoreCase("-")) {
            CharSequence ch="(";
            if (name.contains(ch)) {
                String fname=null;
                fname=name.substring(0,1).toUpperCase()+
                        name.substring(1, name.indexOf("(")).toLowerCase()+
                        name.substring(name.indexOf("("), name.length());
                return fname;
            }
            else {
                String fname=null;
                fname=name.substring(0,1).toUpperCase()+name.substring(1, name.length()).toLowerCase();
                return fname;
            }
        }
        else 
            return "-";
    }
    
    /**
     * Converts the time into hours and minutes
     * @param time the time to be formatted
     * @return formatted time for display
     */
    private String transitimeFormatter(int time) {
        String fTime = time/60 + "h " + time%60 +"m";
        return fTime;
    }
    
    /**
     * Set the ComboFlight details
     * @param comboFlights is the comboFlight object
     */
    public void setTable(ComboFlight[] comboFlights) {
        
        Flight spiceJet=null;
        Flight silkAir=null;
        this.comboFlights=comboFlights;
        flights=new Object[comboFlights.length][12];
        
        originCity.setText(comboFlights[0].getSeg1().getFlight().getOrigin());
        destinationCity.setText(comboFlights[0].getSeg2().getFlight().getDestination());
        DateTimeFormatter dtfOut = DateTimeFormat.forPattern("dd/MM/yyyy");
        DateTimeFormatter timeOut = DateTimeFormat.forPattern("hh:mm aa");
        travelDate.setText(dtfOut.print(comboFlights[0].getSeg1().getDepartureDate()));
        
        for(int i=0;i<comboFlights.length;i++) {
            
            spiceJet=comboFlights[i].getSeg1().getFlight();
            silkAir=comboFlights[i].getSeg2().getFlight();
            flights[i][0]=spiceJet.getFlightno();
            flights[i][1]=cityNameFormatter(spiceJet.getVia());
            flights[i][2]=timeOut.print(comboFlights[i].getSeg1().getDepartureDate());
            flights[i][3]=timeOut.print(comboFlights[i].getSeg1().getArrivalDate());
            flights[i][4]=comboFlights[i].getSeg1().getNoOfPassenger();
            flights[i][5]=silkAir.getFlightno();
            flights[i][6]=cityNameFormatter(silkAir.getOrigin());
            flights[i][7]=transitimeFormatter(comboFlights[i].getTransitTime());
            flights[i][8]=timeOut.print(comboFlights[i].getSeg2().getDepartureDate());
            flights[i][9]=timeOut.print(comboFlights[i].getSeg2().getArrivalDate());
            flights[i][10]=comboFlights[i].getSeg2().getNoOfPassenger();
            flights[i][11]=transitimeFormatter(comboFlights[i].getTotatTravelTime());
        }
            
        jTable1.setModel(new DefaultTableModel(
        flights,
        new String [] {
            "SpiceJet", "via", "Dept. Time", "Arrival Time", "Seats",
            "SilkAir", "From", "Transit Time", "Dept. Time", "Arrival Time", 
            "Seats", "Total Time"
            }));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel destinationCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel originCity;
    private javax.swing.JLabel travelDate;
    // End of variables declaration//GEN-END:variables
}
